#!/bin/bash
# archivo es el nombre del archivo 

if [ $# -ne 1 ]; then
  echo "Uso: $0 <archivo>"
  exit 1
fi

archivo="$1"


if [ ! -e "$archivo" ]; then
  echo "El archivo $archivo no existe."
  exit 2
fi

permisos=$(stat -c "%A" "$archivo")

get_permissions_verbose() {
  local perms="$1"
  usuario=${perms:1:3}
  grupo=${perms:4:3}
  otros=${perms:7:3}

  echo "Permisos del usuario:"
  [[ "${usuario:0:1}" == "r" ]] && echo "- Lectura"
  [[ "${usuario:1:1}" == "w" ]] && echo "- Escritura"
  [[ "${usuario:2:1}" == "x" ]] && echo "- Ejecución"

  echo "Permisos del grupo:"
  [[ "${grupo:0:1}" == "r" ]] && echo "- Lectura"
  [[ "${grupo:1:1}" == "w" ]] && echo "- Escritura"
  [[ "${grupo:2:1}" == "x" ]] && echo "- Ejecución"

  echo "Permisos de otros usuarios:"
  [[ "${otros:0:1}" == "r" ]] && echo "- Lectura"
  [[ "${otros:1:1}" == "w" ]] && echo "- Escritura"
  [[ "${otros:2:1}" == "x" ]] && echo "- Ejecución"
}

get_permissions_verbose "$permisos"
